"""
infrastructure/s3.py — AWS S3 client and storage operations.

A single shared boto3 client is created at module load time with the correct
SigV4 configuration for regional endpoints.  All functions reuse this client —
no per-call client creation.

Required env vars:
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  AWS_REGION         (default: ap-southeast-2)
  S3_BUCKET_NAME
"""

import asyncio
import os
import uuid

import boto3
from botocore.config import Config
from botocore.exceptions import ClientError

# ---------------------------------------------------------------------------
# Shared S3 client (created once at startup)
# ---------------------------------------------------------------------------
# Config(signature_version='s3v4') is required for presigned PUT URLs in
# non-us-east-1 regions (e.g. ap-southeast-2). Without it boto3 defaults to
# SigV2, which S3 rejects with 403 for regional endpoints.
s3_client = boto3.client(
    "s3",
    aws_access_key_id=os.environ.get("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.environ.get("AWS_SECRET_ACCESS_KEY"),
    region_name=os.environ.get("AWS_REGION", "ap-southeast-2"),
    config=Config(signature_version="s3v4"),
)

S3_BUCKET_NAME: str = os.environ.get("S3_BUCKET_NAME", "")


# ---------------------------------------------------------------------------
# Storage operations
# ---------------------------------------------------------------------------

async def upload_to_s3(file_content: bytes, filename: str | None = None) -> str | None:
    """
    Upload raw bytes to S3 and return the generated object key.
    Returns None on failure.
    """
    object_key = str(uuid.uuid4())
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(
            None,
            lambda: s3_client.put_object(
                Bucket=S3_BUCKET_NAME,
                Key=object_key,
                Body=file_content,
                ContentType="application/pdf",
            ),
        )
        return object_key
    except ClientError as e:
        print(f"Error uploading to S3: {e}")
        return None


async def download_from_s3(object_key: str) -> bytes | None:
    """
    Download an object from S3 and return its bytes.
    Returns None on failure.
    """
    loop = asyncio.get_event_loop()
    try:
        def _download():
            response = s3_client.get_object(Bucket=S3_BUCKET_NAME, Key=object_key)
            return response["Body"].read()

        return await loop.run_in_executor(None, _download)
    except ClientError as e:
        print(f"Error downloading from S3: {e}")
        return None


async def get_pdf_from_s3(s3_object_key: str) -> bytes:
    """
    Download a PDF from S3 and return its bytes.
    Raises RuntimeError on failure (used by evaluation pipeline which needs
    hard failures rather than silent None returns).
    """
    loop = asyncio.get_event_loop()
    try:
        def _download():
            response = s3_client.get_object(Bucket=S3_BUCKET_NAME, Key=s3_object_key)
            return response["Body"].read()

        return await loop.run_in_executor(None, _download)
    except ClientError as e:
        raise RuntimeError(f"Failed to download {s3_object_key} from S3: {e}")


async def generate_presigned_url(object_key: str, expiration: int = 3600) -> str | None:
    """
    Generate a presigned GET URL for an existing S3 object.
    Returns None on failure.
    """
    try:
        return s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": S3_BUCKET_NAME, "Key": object_key},
            ExpiresIn=expiration,
        )
    except ClientError as e:
        print(f"Error generating presigned GET URL: {e}")
        return None


async def generate_presigned_upload_url(
    object_key: str,
    content_type: str = "application/pdf",
    expiration: int = 900,
) -> str | None:
    """
    Generate a presigned PUT URL so the client can upload directly to S3
    without routing file bytes through the backend server.

    ContentType is intentionally excluded from the signed Params — including
    it makes it a required signed header, which S3 rejects if the browser
    sends even a slightly different value (charset, capitalisation, etc.).

    Args:
        object_key:   The S3 key to write to (generated by the caller).
        content_type: Kept for API compatibility; not signed. (default: application/pdf)
        expiration:   URL TTL in seconds (default: 15 minutes).

    Returns:
        The presigned URL string, or None on error.
    """
    try:
        return s3_client.generate_presigned_url(
            "put_object",
            Params={"Bucket": S3_BUCKET_NAME, "Key": object_key},
            ExpiresIn=expiration,
        )
    except ClientError as e:
        print(f"Error generating presigned PUT URL: {e}")
        return None
